[package]
name = "editor"
version = "1.0.1"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"

[dependencies.web-sys]
version = "0.3.77"
features = [ "console" ]

[lib]
crate-type = ["cdylib", "rlib"]
